name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liQSBq0XtIyBeVh3"
GITHUB_OWNER = "32963360"
GITHUB_REPO = "kkkdh"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://kkkdh-6s7.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://kkkdh-6s7.pages.dev/"

